Split models to entities and services
dbaltas/commit-sniffer pull request #19
Opened 2017-10-01 14:44 UTC by mylk

This is just a separation of models to database models (entities) and services, those having more operational role.

At the same time made renamed two of the services

- app/Models/GitLogRunner.php -> app/Services/ParserService.php
  Maybe should have been renamed earlier (gitLog is now a "plugin" https://github.com/dbaltas/commit-sniffer/pull/9 and this is more generic now). Named it "parser" as it parses the commit messages.

- app/Models/Parser.php -> app/Services/ReporterService.php
  Named it "reporter" as it reads from the database the commits, categorizes them and prepares the data for the output. Not that nice name, but coulnd't think of another.

@dbaltas naming is not final, we can change it if you prefer other names.

2017-10-01 19:11 UTC, dbaltas commented
makes total sense. Kudos! @mylk you'll have to resolve conflicts to proceed with this one

2017-10-02 20:19 UTC, mylk commented
Tnx @dbaltas! Here you go!

2017-10-03 11:53 UTC, dbaltas requested changes

2017-10-03 11:53 UTC, dbaltas commented on app/Console/Commands/RepoStats.php
> +        $parser = new ReporterService();
rename to `$reporter`

2017-10-03 19:48 UTC, mylk commented
Oops! Fixed.

2017-10-04 08:42 UTC, merged